### ISSUE TITLE
莫名其妙生成默认分组

### ISSUE THREAD

**Issue by Steven-WZH** [halo-sigs/plugin-links#10]
![image](https://user-images.githubusercontent.com/113268133/218300300-4ccce34a-c5e6-4046-98b1-cf842e872003.png)
以前把默认分组都删了的，现在重启了docker又出来了

**Comment by JohnNiang** [comment]
可能是插件初始化的时候，又初始化了分组。

**Comment by Steven-WZH** [comment]
有啥解决办法嘛

**Comment by JohnNiang** [comment]
非常欢迎提交一个 Pull Request 删除 <https://github.com/halo-sigs/plugin-links/blob/main/src/main/resources/extensions/groups.yaml>。

PR 合并后，我们会尝试发布一个新的插件版本。

**Comment by ruibaby** [comment]
很奇怪，我重启之后默认分组被重置了，导致失去了链接关联。

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/21301288/219007517-32127577-037e-489c-8ad6-7ff82d180ffc.png">

/cc @halo-sigs/halo

**Comment by guqing** [comment]
应该将插件下添加默认分组的 yaml 删除，这不是必须的。否则在 extension 下的 yaml 就是会在启动时覆盖掉数据库中的，之前的讨论是，如果只有安装时需要初始化的资源应该在安装时初始化一次，然后后续升级通过 merge 的方式添加新字段且不能覆盖已有的值（待定）

**Comment by ruibaby** [comment]
@guqing https://github.com/halo-sigs/plugin-links/pull/11

**Comment by guqing** [comment]
由于写 plugin-links 时 reconciler 还无法在插件中使用，因此结构只能使用 group 下的 children 来维护分组下有哪些 links，这个结构也会导致默认添加分组，用户在此分组下添加 link 启动时就会被覆盖

**Comment by Steven-WZH** [comment]
那啥时候把这个bug修掉(

**Comment by guqing** [comment]
> 那啥时候把这个bug修掉(

已经修复了，但是还没有发版本，我们还需要对其中一些实现做一下兼容处理并充分测试后才能发布版本，以防止出现升级问题
