### ISSUE TITLE
希望 Link 支持排序

### ISSUE THREAD

**Issue by guqing** [halo-sigs/plugin-links#12]
目前 Link 无法在界面上排序，可以先简单支持通过设置数值的方式排序，像 1.x 一样。

/kind feature

**Comment by ruibaby** [comment]
<img width="1078" alt="image" src="https://user-images.githubusercontent.com/21301288/219044815-2f65f78c-0887-4aac-877e-1d67c13a5792.png">

**Comment by guqing** [comment]
> <img alt="image" width="1078" src="https://user-images.githubusercontent.com/21301288/219044815-2f65f78c-0887-4aac-877e-1d67c13a5792.png">

鬼才，居然已经有了
