### ISSUE TITLE
创建链接，再删除链接，左侧的链接数量只增不减？

### ISSUE THREAD

**Issue by stkroot** [halo-sigs/plugin-links#16]
创建3个链接，然后全部删除，左侧链接数量还是显示3个链接。

**Comment by zjy4fun** [comment]
<img width="1446" alt="image" src="https://user-images.githubusercontent.com/106857035/235849694-6ea3e10a-4214-481c-8d43-a2f51aa32c2f.png">

应该是“删除成功” 的 toast 的时间太长，导致刷新请求操作晚了一点

**Comment by guqing** [comment]
该问题可能已经修复了，我先关闭此 issue 如果还有问题则重新打开
/close
