### ISSUE TITLE
重启halo链接消失

### ISSUE THREAD

**Issue by CV-Devlau** [halo-sigs/plugin-links#17]
## halo版本
2.3.0
## 部署方式
docker H2数据库

## 插件版本
1.10
## 问题
修改分组名称为：  -           （不确定是不是因为这个）
添加连接后，重启Halo，添加的分组和链接消失。

左边恢复为默认分组，显示一个链接，分页显示有两页，但看不到链接

![image](https://user-images.githubusercontent.com/63354237/224542539-4fbe32ba-5930-4e9b-9fe5-fea23cc69761.png)
分组接口links返回一个halo
![image](https://user-images.githubusercontent.com/63354237/224542631-a7768465-ed1d-404b-8a92-7cb45e8fe61b.png)

links接口传入了查询参数 /apis/core.halo.run/v1alpha1/links?fieldSelector=name%3D(halo)，去掉后可以查出原来的链接
![image](https://user-images.githubusercontent.com/63354237/224542785-44ba80a8-b0b0-4d72-a9b6-5b5e6323d75c.png)

**Comment by JohnNiang** [comment]
当前这个问题可能在 https://github.com/halo-sigs/plugin-links/pull/11 已经解决了，建议等待插件发布 1.1.1。

/ping @halo-sigs/halo
