### ISSUE TITLE
建议logo输入右侧增加按钮（上传或选择图片）

### ISSUE THREAD

**Issue by YuJian95** [halo-sigs/plugin-links#26]
如图所示，在logo 右侧增加按钮，参考主题相关设置，方便选择图片：

![image](https://github.com/halo-sigs/plugin-links/assets/37510077/1f9243d7-ebd8-4f49-8b7b-0a56150220f2)

![image](https://github.com/halo-sigs/plugin-links/assets/37510077/bf5ea728-1462-4de9-9f8e-d0c4c812091b)

**Comment by zcns** [comment]
HI @YuJian95 Your update issue has been confirmed and is currently under development.
