### ISSUE TITLE
run.halo.links.vo 包下的类没有实现run.halo.app.theme.finders.vo.ExtensionVoOperator 接口

### ISSUE THREAD

**Issue by Roozenlz** [halo-sigs/plugin-links#42]
如题，导致主题中使用以下语法
![image](https://github.com/halo-sigs/plugin-links/assets/93673944/66f499d5-10d8-4938-8e51-b86f394bac3e)

将报如下错误
![image](https://github.com/halo-sigs/plugin-links/assets/93673944/74e5ac6f-45f3-43e0-a82b-108f056b2f5b)

**Comment by JohnNiang** [comment]
目前仅能对实现了 `run.halo.app.theme.finders.vo.ExtensionVoOperator` 接口的 VO 才能直接调用 `annotations.#method`。

从源码上看，`src/main/java/run/halo/links/vo/LinkGroupVo.java` 并未实现该接口。

https://github.com/halo-sigs/plugin-links/blob/48230cfd2daa9ccb50f5bbc14e01e50fcc5455c2/src/main/java/run/halo/links/vo/LinkGroupVo.java#L16

**Comment by Roozenlz** [comment]
是这样的，我就是这个意思，所以想能不能优化一下，不然主题端没法用这种语法

**Comment by JohnNiang** [comment]
Hi @Roozenlz ，如果有兴趣的话，欢迎提交 PR 来支持这个功能。目前仅需要让下面这个类实现 `run.halo.app.theme.finders.vo.ExtensionVoOperator` 接口即可。

https://github.com/halo-sigs/plugin-links/blob/48230cfd2daa9ccb50f5bbc14e01e50fcc5455c2/src/main/java/run/halo/links/vo/LinkGroupVo.java#L16

**Comment by Roozenlz** [comment]
好的，我试着做一下
