### ISSUE TITLE
期望添加友链搜索功能

### ISSUE THREAD

**Issue by HowieHz** [halo-sigs/plugin-links#57]
我有很多友链要添加，那个添加选择附件的页面也不支持搜索，一个一个找太坐牢了
可否添加自动匹配，如https://xxxxx.xxx -> 自动匹配到 upload/https_xxxxx_xxx.ico 使用该图像作为Logo

更好的是优先匹配名字不考虑后缀，比如有多个网址https://a.com, http://b.com
附件库里面有 https_a_com.png，https_b_com.ico，能自动匹配上对应的Logo

进一步附件库里面有https_a_com.png，https_a_com.ico，可以优先选择分辨率高的或者优先选择某一格式的

**Comment by JohnNiang** [comment]
Hi @HowieHz , thank you for reaching out here!

IMO，当前需求太客制化，不是很通用，尤其是需要针对友链的 Logo 做专门的附件匹配。

不过，关于你提到的附件搜索功能，我认为是可以考虑加上的。

/kind feature
/retitle 期望添加友链搜索功能

**Comment by ruibaby** [comment]
我觉得根据链接自动去找网站的 icon 链接是可行的，去附件找这个需求确实有点客制。

**Comment by HowieHz** [comment]
> Hi @HowieHz , thank you for reaching out here!
> 
> IMO，当前需求太客制化，不是很通用，尤其是需要针对友链的 Logo 做专门的附件匹配。
> 
> 不过，关于你提到的附件搜索功能，我认为是可以考虑加上的。
> 
> /kind feature /retitle 期望添加友链搜索功能

添加一些api，让图标自动获取是否可行？
下面第一个比较好用速度也快，第二个限制了16*16png，第三个不能带https://和http://前面两个可以
http://www.getfavicon.org/get.pl?url={url}&submitget=get+favicon
http://www.google.com/s2/favicons?domain={url}
https://api.iowen.cn/favicon/{url}.png

但是api获取有个缺点，就是实际上网站有<link rel="icon">和<link rel="shortcut icon">标签的话会覆盖掉网站根目录/favicon.ico，导致获取到的和实际上的不同，这些天自己研究写了个解析器可能可以作为参考www
https://github.com/HowieHz/get_favicon/blob/main/src/api/browser_emulation_api.py

**Comment by ruibaby** [comment]
我的建议也是不用第三方 API 去获取 favicon，直接在后端提供一个接口，使用 jsoup 去解析网页找 `link rel="icon"` 即可。

**Comment by LIlGG** [comment]
这个问题应该可以在 #72 中得到满足。

see #71
