### ISSUE TITLE
获取图库分组接口返回的数据中缺少 links 数据

### ISSUE THREAD

**Issue by wan92hen** [halo-sigs/plugin-links#58]
`GET /apis/core.halo.run/v1alpha1/linkgroups` 及 `GET /apis/core.halo.run/v1alpha1/linkgroups/{name}` 接口返回数据包含 `spec.links` 字段，但值为空。
![image](https://github.com/halo-sigs/plugin-links/assets/27671436/8c080cdb-2369-4690-b778-77055bff4b3a)

**Comment by guqing** [comment]
分组下的 links 属性已经在 1.2.0 就被标记为过时，不再使用，只是一直没有移除 https://github.com/halo-sigs/plugin-links/blob/b75e01e4b187a26da02163dfdc016d856fe4b0f4/src/main/java/run/halo/links/LinkGroup.java#L30

/close
