### ISSUE TITLE
Cannot Jump to URL after Clicking Hyperlink

### ISSUE THREAD

**Issue by zzudongxiang** [halo-sigs/plugin-links#6]
Cannot Jump to URL after Clicking Hyperlink

![image](https://user-images.githubusercontent.com/33760061/211270074-c64e9283-4107-42ef-9feb-87d0ddcdf023.png)

**Comment by JohnNiang** [comment]
Hi @zzudongxiang , thank you for reaching out here.

该问题已经修复了，请参考：<https://github.com/halo-dev/theme-earth/issues/35>。

建议下载最新的主题重试一下。

**Comment by zzudongxiang** [comment]
已解决, 感谢~
