### ISSUE TITLE
分组下无数据，前台能遍历到

### ISSUE THREAD

**Issue by adozhao** [halo-sigs/plugin-links#60]
`全部`这个分组下没有链接，数据都放到其他的分组下了，然而在前台模板遍历时候却能遍历到，且为空对象，应对分组进行过滤 [点击查看](https://ado.zone/links)
![image](https://github.com/halo-sigs/plugin-links/assets/23180747/8cbdf25b-c808-4f9e-a00c-2557413f8bdf)
![image](https://github.com/halo-sigs/plugin-links/assets/23180747/6e3822cd-1bcd-4501-a989-1f57101cb52e)

**Comment by LIlGG** [comment]
/close 

see #65
