### ISSUE TITLE
要是没有logo的话可以给前端返回一个和后台一样的文字头像吗

### ISSUE THREAD

**Issue by Anyexyz** [halo-sigs/plugin-links#61]
链接目前是允许Logo为空的，那么为空的时候可以给前端返回一个和后台一样的文字头像吗

**Comment by Anyexyz** [comment]
类似这种接口提供的功能https://ui-avatars.com/api/?name=Hello
在原LOGO加载失败或者没有logo的时候加载

**Comment by LIlGG** [comment]
后台目前链接为空时并不是一个头像，而是一个文本占位符，取了用户 name 的第一个字符。

https://github.com/halo-dev/halo/blob/ebf1a1fe1b5b9d89eff1404bca1269f9f29b4f30/ui/packages/components/src/components/avatar/Avatar.vue#L86-L99

因此建议主题端自行处理没有用户 logo 的情况。例如放一个默认图，或者采用和 Halo 同样的方式。

**Comment by ruibaby** [comment]
> 后台目前链接为空时并不是一个头像，而是一个文本占位符，取了用户 name 的第一个字符。
> 
> [halo-dev/halo@`ebf1a1f`/ui/packages/components/src/components/avatar/Avatar.vue#L86-L99](https://github.com/halo-dev/halo/blob/ebf1a1fe1b5b9d89eff1404bca1269f9f29b4f30/ui/packages/components/src/components/avatar/Avatar.vue#L86-L99)
> 
> 因此建议主题端自行处理没有用户 logo 的情况。例如放一个默认图，或者采用和 Halo 同样的方式。

+1，这应该是前端需要做的事情。

/close
