### ISSUE TITLE
请问一下linkfinder中的listby方法中删除时间不能为空有什么意义吗？

### ISSUE THREAD

**Issue by yangkuan1985** [halo-sigs/plugin-links#64]
![image](https://github.com/halo-sigs/plugin-links/assets/27803161/cf080119-8b72-48dc-8804-98497159ed4f)
在我使用的时候添加一个分组，在模版页面使用时使用listby获取分组下的链接不能获取到链接。
查看代码可能是上图那句删除时间不能为空引起的，有没有大神指导一下为什么要这样。

**Comment by guqing** [comment]
应该是条件写反了
