### ISSUE TITLE
找不到Console 左侧的链接菜单项

### ISSUE THREAD

**Issue by abcxiaobu** [halo-sigs/plugin-links#83]
找不到Console 左侧的链接菜单项啊

**Comment by abcxiaobu** [comment]
![Uploading f564be0164fc78d8e58cc981bbb5fe1.png…]()

**Comment by abcxiaobu** [comment]
侧边栏没有啊
<img width="1088" alt="f564be0164fc78d8e58cc981bbb5fe1" src="https://github.com/user-attachments/assets/3fe2fa36-84d8-4983-bca8-b75b2bd335f8">
这个添加链接也试过了没有反应啊
<img width="214" alt="3f90be74aa35b940eba85061ed356a1" src="https://github.com/user-attachments/assets/7527c5d4-196d-43aa-b876-3dd24d0adeb0">
网址 https://www.xiaobu.xyz

**Comment by ruibaby** [comment]
检查 `/apis/api.console.halo.run/v1alpha1/plugins/-/bundle.js` 和 `/apis/api.console.halo.run/v1alpha1/plugins/-/bundle.css` 是不是被你的 CDN 或者反向代理缓存了。

**Comment by abcxiaobu** [comment]
哦哦,感谢!
