### ISSUE TITLE
新增super-role角色无链接管理权限

### ISSUE THREAD

**Issue by zzudongxiang** [halo-sigs/plugin-links#9]
问题版本：
- Halo版本2.2.0
- plugin-links版本1.1.0

复现步骤：
1. 新增用户，并给用户赋予super-role权限
2. 安装plugin-links插件，并启用插件
3. 新增用户无链接的编辑、查看等权限
4. 切换admin账户后有相关的编辑权限

**Comment by guqing** [comment]
<img width="1920" alt="image" src="https://user-images.githubusercontent.com/38999863/217134281-cf1c1ce4-2245-4939-85e3-81351a9127d6.png">
checkout 到 release-2.2 tag 并按照上述复现步骤没有复现，你们试一下 @halo-sigs/halo

**Comment by guqing** [comment]
Hi @zzudongxiang，你说的赋予新建的用户 super-role 权限是直接给已有的 super-role 角色还是创建一个新角色勾选全部

**Comment by guqing** [comment]
> Hi @zzudongxiang，你说的赋予新建的用户 super-role 权限是直接给已有的 super-role 角色还是创建一个新角色勾选全部

我尝试了此种情况发现确实有问题，原因是 links group 的 role template 配置有问题导致给予了权限确 403
> http://localhost:8090/apis/core.halo.run/v1alpha1/linkgroups
需要修改 roleTemplate.yaml 加上 linkgroups 的权限，目前看到只有 links 相关的
<img width="542" alt="image" src="https://user-images.githubusercontent.com/38999863/217135347-00e8e1e6-5e7f-46d1-8dc6-dc1802905fc4.png">

**Comment by guqing** [comment]
已在 #15 修复，我先关闭此 issue
