### ISSUE TITLE
基本设置失效

### ISSUE THREAD

**Issue by QYG2297248353** [halo-sigs/plugin-links#90]
在基本设置中修改 `页面标题`
![image](https://github.com/user-attachments/assets/e356e581-7c4e-4fad-866b-85574ac77528)

打开 `links` 后 标题没有变化
![image](https://github.com/user-attachments/assets/218458b0-26fe-4c15-99c7-4d8296aff956)

**Comment by ruibaby** [comment]
> /cc @ruibaby

当前插件的实现有两个问题：

1. 插件提供的变量名为 title，而大部分主题模板中可能因为 layout.html 也会有一个 title 变量导致冲突。所以建议此插件暴露的变量改名。
2. 主题必须适配，尤其是 page title，所以很容易被忽略。https://github.com/halo-dev/halo/issues/2736

**Comment by LIlGG** [comment]
> > /cc @ruibaby
> 
> 当前插件的实现有两个问题：
> 
> 1. 插件提供的变量名为 title，而大部分主题模板中可能因为 layout.html 也会有一个 title 变量导致冲突。所以建议此插件暴露的变量改名。
> 2. 主题必须适配，尤其是 page title，所以很容易被忽略。[为主题的 head 标签部分提供 title 变量 halo-dev/halo#2736](https://github.com/halo-dev/halo/issues/2736)

链接插件中的变量名为 `linksTitle` 而不是 `title`，所以我认为这里可能是主题端所设置的。

https://github.com/halo-sigs/plugin-links/blob/01bdf3b8c18ba0a6022e9ee69f7ced7c6461489e/src/main/java/run/halo/links/LinkRouter.java#L62
