### ISSUE TITLE
关联文章，默认是必选的。 导致无法做成正常跳转链接。

### ISSUE THREAD

**Issue by alannewlife** [halo-sigs/plugin-links#96]
![Image](https://github.com/user-attachments/assets/50f68110-0a0e-4a60-974d-46af04fe42e0)

我这里的关联文章，默认是必选的。
导致无法做成正常跳转链接。

这是bug么。

**Comment by ruibaby** [comment]
这不是这个插件提供的设置选项，应该是你使用的主题或者其他插件扩展的表单，所以请向你使用的主题或者其他插件反馈。

/triage unresolved

**Comment by alannewlife** [comment]
好的，谢谢。
试了很多主题，也不知道是哪个弄出来的了。
